### PR TITLE
Make Olivier's submission asynchronous

### PR DESCRIPTION
**Pull request by ogregoire**
I updated this on Code Golf, and I got a 50% speed boost with 8 processors. I don't expect the speed gain to be that good, but probably substantially higher than the current implementation.

### CODE REVIEW

**Comment by omertuc** [comment]
Seems to be substantially worse (on the main branch your submission does 5GiB/s):
image

**Comment by ogregoire** [comment]
I must say I'm a bit surprised of this result that you have.

I should probably reduce the number of threads to the number of CPU minus one.

I couldn't start my machine recently because of private life situations, but I will definitely try. So please keep this PR open as I will amend it.

**Comment by omertuc** [comment]
Gave it another try:

image

Looks better now

Also seems that the Java process doesn't die when I kill the measurement Python with ctrl+c so maybe some leftover processes from before were using up my cores when I tested it previously and that explains the low throughput

**Comment by ogregoire** [comment]
Great! Then I'd like to push it, if possible.

**Comment by omertuc** [comment]
Will update golf thread shortly

**Pull request merged**
